submodule-aware packager (from master), changed submodule SHA extraction

diff --git a/contrib/package b/contrib/package
--- a/contrib/package
+++ b/contrib/package
@@ -2,41 +2,48 @@
 
 set -e
 
-GIT_TAG=${1}
-PKG_PATH=${2}
-PREFIX="dbrelay"
-
-if [ "${GIT_TAG}" = "" -o "${PKG_PATH}" = "" ]; then
-  echo "Syntax: ${0} <tag> <path>"
-  echo "        The result will be written out to <path>/${PREFIX}_<tag>.tgz"
-  exit 1
-fi
-
-BUILD_FILE="${PREFIX}_${GIT_TAG}"
-BUILD_DIR="${PKG_PATH}/${BUILD_FILE}"
-
-mkdir ${BUILD_DIR} || {
-  echo "Unable to create the package directory: ${BUILD_DIR}"
+[ "${1}" ] || {
+  echo "Syntax: ${0} <path>"
+  echo "        The result will be written out to <path>/${PREFIX}_<COMMIT_DATE>.tgz"
   exit 1
 }
 
+pushd ${1} > /dev/null
+  PKG_PATH=${PWD}
+popd > /dev/null
 
-BUILD_TGZ="${BUILD_DIR}.tgz"
-VER_FILE="${BUILD_DIR}/html/version.json"
+PREFIX="dbrelay"
+SUBMODULE_PATH="src/ngx_dbrelay"
 
 pushd $(dirname ${0})/.. > /dev/null
 
-git archive --format=tar ${GIT_TAG} . | (cd ${BUILD_DIR}; tar xfp -)
+  SUBMODULE_SHA=$(git submodule src/ngx_dbrelay | sed -e 's/^.\([^ ]*\) .*$/\1/')
+  COMMIT_DATE=$(git log -n 1 --pretty=format:"%ci" | sed -e 's/ .*//' -e 's/-//g' -e 's/^20//')
 
-git log -n 1 ${GIT_TAG} --pretty=format:"{ 'committer': '%an', 'tag': '${GIT_TAG}', 'revision': '%H', 'date_rfc': '%cD', 'date_epoc': '%ct' }" > ${VER_FILE}
+  GIT_TAG=$(git rev-parse HEAD)
+  BUILD_FILE="${PREFIX}_${COMMIT_DATE}"
+  BUILD_DIR="${PKG_PATH}/${BUILD_FILE}"
 
-pushd ${PKG_PATH} > /dev/null
+  mkdir ${BUILD_DIR} || {
+    echo "Unable to create the package directory: ${BUILD_DIR}"
+    exit 1
+  }
 
-# Snow Leopard no longer supports --owner and --group options in tar. Amazing.
-# tar -czf ${BUILD_TGZ} --owner=0 --group=0 --numeric-owner ./${BUILD_FILE}
+  BUILD_TGZ="${BUILD_DIR}.tgz"
+  VER_FILE="${BUILD_DIR}/html/version.json"
 
-tar -czf ${BUILD_TGZ} --numeric-owner ./${BUILD_FILE}
-rm -rf ./${BUILD_FILE}
+  git archive --format=tar ${GIT_TAG} . | (cd ${BUILD_DIR}; tar xfp -)
 
+  pushd ${SUBMODULE_PATH} > /dev/null
+    git archive --format=tar ${SUBMODULE_SHA} . | (cd ${BUILD_DIR}/${SUBMODULE_PATH}; tar xfp -)
+  popd > /dev/null
+
+  git log -n 1 ${GIT_TAG} --pretty=format:"{ 'committer': '%an', 'sha': '${GIT_TAG}', 'revision': '%H', 'date_rfc': '%cD', 'date_epoc': '%ct' }" > ${VER_FILE}
+
+  pushd ${PKG_PATH} > /dev/null
+    tar -czf ${BUILD_TGZ} --numeric-owner ./${BUILD_FILE}
+    rm -rf ./${BUILD_FILE}
+  popd > /dev/null
 popd > /dev/null
-popd > /dev/null
+
+echo "Check the ${PKG_PATH}/${BUILD_TGZ} file"
