fix to mysql error handling and preliminary odbc stuff
git-svn-id: https://viaduct.svn.beanstalkapp.com/code/trunk/viaduct@122 c97fca75-8364-49ce-9f5b-20eef4eea7b5

diff --git a/src/ngx_http_viaduct/configure b/src/ngx_http_viaduct/configure
--- a/src/ngx_http_viaduct/configure
+++ b/src/ngx_http_viaduct/configure
@@ -696,6 +696,8 @@ FREETDS_TRUE
 FREETDS_FALSE
 MYSQL_TRUE
 MYSQL_FALSE
+ODBC_TRUE
+ODBC_FALSE
 CPP
 GREP
 EGREP
@@ -1296,6 +1298,7 @@ Optional Packages:
   --with-nginx=DIR        build with support for nginx in DIR
   --with-freetds=DIR      build with support for FreeTDS in DIR
   --with-mysql=DIR        build with support for MySQL in DIR
+  --with-odbc=DIR         build with support for ODBC in DIR
 
 Some influential environment variables:
   CC          C compiler command
@@ -3380,7 +3383,7 @@ if test "$with_mysql"; then
 	mysql=true
         DB_INCS="-I $with_mysql/include"
         #CPPFLAGS="$CPPFLAGS $DB_INCS"
-        DB_LIBS="-L $with_mysql/lib/ -lmysqlclient"
+        DB_LIBS="$with_mysql/lib/libmysqlclient.a -lssl"
         #LDFLAGS="$LDFLAGS $DB_LIBS"
 
 cat >>confdefs.h <<\_ACEOF
@@ -3398,6 +3401,38 @@ fi
 else
   MYSQL_TRUE='#'
   MYSQL_FALSE=
+fi
+
+
+
+# Check whether --with-odbc was given.
+if test "${with_odbc+set}" = set; then
+  withval=$with_odbc;
+fi
+
+if test "$with_odbc"; then
+        if echo "$with_odbc" | grep -v '^/'; then
+                with_odbc="$PWD/$with_odbc"
+        fi
+        odbc=true
+        DB_INCS="-I$with_odbc/include"
+        DB_LIBS="$with_odbc/odbc/.libs/libtdsodbc.a"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ODBC 1
+_ACEOF
+
+
+
+        DB_MODULE="odbc.c"
+
+fi
+ if test "$odbc" = "true"; then
+  ODBC_TRUE=
+  ODBC_FALSE='#'
+else
+  ODBC_TRUE='#'
+  ODBC_FALSE=
 fi
 
 
@@ -4217,7 +4252,72 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_iconv_open" >&5
 echo "${ECHO_T}$ac_cv_lib_iconv_iconv_open" >&6; }
 if test $ac_cv_lib_iconv_iconv_open = yes; then
-  VIADUCT_EXTRA_LIBS="-liconv"
+  VIADUCT_EXTRA_LIBS="$VIADUCT_EXTRA_LIBS -liconv"
+fi
+
+{ echo "$as_me:$LINENO: checking for clock_gettime in -lrt" >&5
+echo $ECHO_N "checking for clock_gettime in -lrt... $ECHO_C" >&6; }
+if test "${ac_cv_lib_rt_clock_gettime+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lrt  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char clock_gettime ();
+int
+main ()
+{
+return clock_gettime ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_rt_clock_gettime=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_rt_clock_gettime=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_rt_clock_gettime" >&5
+echo "${ECHO_T}$ac_cv_lib_rt_clock_gettime" >&6; }
+if test $ac_cv_lib_rt_clock_gettime = yes; then
+  VIADUCT_EXTRA_LIBS="$VIADUCT_EXTRA_LIBS -lrt"
 fi
 
 
@@ -4403,6 +4503,13 @@ if test -z "${MYSQL_TRUE}" && test -z "${MYSQL_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"MYSQL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"MYSQL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ODBC_TRUE}" && test -z "${ODBC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ODBC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ODBC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5022,6 +5129,8 @@ FREETDS_TRUE!$FREETDS_TRUE$ac_delim
 FREETDS_FALSE!$FREETDS_FALSE$ac_delim
 MYSQL_TRUE!$MYSQL_TRUE$ac_delim
 MYSQL_FALSE!$MYSQL_FALSE$ac_delim
+ODBC_TRUE!$ODBC_TRUE$ac_delim
+ODBC_FALSE!$ODBC_FALSE$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
@@ -5030,7 +5139,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 88; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 90; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
